volumes:
  db:
services:
  postgres:
    image: postgres:16.9
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
  bronson_online:
    image: bronson_online:latest
    container_name: bronson_online
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    build: .
    ports:
      - "7878:7878"
    command: cargo run --profile release -- -p